// Single owner for the default automated gate. package.json may expose
// convenience commands, but it is not a second registry of what `check` means.
//
// Test-plan membership is scheduling, not architectural authority. Every test
// remains subject to docs/ARCHITECTURE.md "Testing architecture": existing
// source-shape/change-detector tests are not grandfathered, and a correct
// refactor should rewrite/delete a brittle test rather than preserve the old
// implementation solely to keep this list green.
export const REPOSITORY_NODE_TESTS = Object.freeze([
  "tests/test-integrations.mjs",
  "tests/test-i18n.mjs",
  "tests/test-test-ownership.mjs",
  "tests/test-thcrap-service.mjs",
  "tests/test-thcrap-compiler.mjs",
  "tests/test-build-profile.mjs",
  "tests/test-runtime-build-profiles.mjs",
  "tests/test-host-workspace.mjs",
  "tests/test-node-environment.mjs",
  "tests/test-language-pack-cache.mjs",
  "tests/test-host-config.mjs",
  "tests/test-self-host-bundle.mjs",
  "tests/test-workspace-layout.mjs",
  "tests/test-browser-module-graph.mjs",
  "tests/test-frontend-manifest.mjs",
  "tests/test-dom-contract.mjs",
  "tests/test-app-shell-contract.mjs",
  "tests/test-app-shell-client.mjs",
  "tests/test-launcher-lifecycle.mjs",
  "tests/test-remote-metadata.mjs",
  "tests/test-resource-mode.mjs",
  "tests/test-product-selection.mjs",
  "tests/test-publication-audit.mjs",
  "tests/test-public-tree-policy.mjs",
  "tests/test-remote-target-policy.mjs",
  "tests/test-product-catalog.mjs",
  "tests/test-runtime-data-provider.mjs",
  "tests/test-runtime-preparation.mjs",
  "tests/test-runtime-generation-lease.mjs",
  "tests/test-runtime-session.mjs",
  "tests/test-runtime-protocol-model.mjs",
  "tests/test-changelog.mjs",
  "tests/test-game-zoom.mjs",
  "tests/test-game-preferences.mjs",
  "tests/test-language-catalog.mjs",
  "tests/test-offline-language-index.mjs",
  "tests/test-language-pack-validation.mjs",
  "tests/test-music-availability.mjs",
  "tests/test-multiplayer-identity.mjs",
  "tests/test-multiplayer-lobby-snapshot.mjs",
  "tests/test-multiplayer-preferences.mjs",
  "tests/test-multiplayer-relay-url.mjs",
  "tests/test-netplay-relay-product-policy.mjs",
  "tests/test-multiplayer-runtime-options.mjs",
  "tests/test-multiplayer-room-session.mjs",
  "tests/test-multiplayer-spectator-rail-position.mjs",
  "tests/test-replay-files.mjs",
  "tests/test-runtime-diagnostics-model.mjs",
  "tests/test-sha256.mjs",
  "tests/test-route-state.mjs",
  "tests/test-site-notice.mjs",
  "tests/test-touch-layout-editor-state.mjs",
  "tests/test-touch-layout-model.mjs",
  "tests/test-touch-runtime-protocol.mjs",
  "tests/test-runtime-release.mjs",
  "tests/test-completion-report.mjs",
  "tests/test-development-host-manifest.mjs",
  "tests/test-development-server-scope.mjs",
  "tests/test-external-resource-routing.mjs",
  "tests/test-publication-host-seed.mjs",
  "tests/test-network-activity.mjs",
  "tests/test-static-content-policy.mjs",
  "tests/test-package-descriptor.mjs",
  "tests/test-package-generation.mjs",
  "tests/test-package-launcher.mjs",
  "tests/test-package-mutation-queue.mjs",
  "tests/test-package-store-contract.mjs",
  "tests/test-package-zip.mjs",
  "tests/test-legacy-game-pack.mjs",
  "tests/test-offline-publication.mjs",
  "tests/test-release-catalog.mjs",
  "tests/test-host-manifest.mjs",
  "tests/test-origin-migration.mjs",
  "tests/test-release-manifest.mjs",
  "tests/test-release-bundle.mjs",
  "tests/test-release-entry.mjs",
  "tests/test-operator-delivery.mjs",
]);

export const REPOSITORY_PYTHON_TESTS = Object.freeze([
  "tests/test_ogg_converter.py",
]);

export const WORKSPACE_PRECHECKS = Object.freeze([]);

export const WORKSPACE_NODE_TESTS = Object.freeze([
  "tests/test-development-host-manifest-workspace.mjs",
  "tests/test-runtime-protocol-contract.mjs",
  "tests/test-preload-data-assembler.mjs",
  "tests/test-runtime-storage-contract.mjs",
  "tests/test-thcrap-upstream-contract.mjs",
  "tests/test-replay-extension-contract.mjs",
  "tests/test-always-hitbox-contract.mjs",
  "tests/test-sdl-emscripten-audio-contract.mjs",
  "tests/test-mobile-frame-pacing.mjs",
  "tests/test-native-frame-pacing.mjs",
  "tests/test-vbo-streaming-contract.mjs",
  "tests/test-sprite-sampling-contract.mjs",
  "tests/test-shell-protocol.mjs",
  "tests/test-server.mjs",
  "tests/test-runtime-release-host-assembly.mjs",
  "tests/test-test-build-cards-browser.mjs",
  "tests/test-th10-runtime-directory.mjs",
]);

export const WORKSPACE_PYTHON_TESTS = Object.freeze([
  "tests/test-touhou-formats.py",
]);
