export const FIRST_USE_NOTICE_FILE = "content/FIRST_USE_NOTICE.html";
export const FIRST_USE_NOTICE_SEEN_STORAGE_KEY = "eagler-touhou-first-use-notice-seen-v1";

const LEGACY_SEEN_STORAGE_KEYS = Object.freeze([
  "eagler-touhou-new-player-notice-seen-v1",
  "eagler-touhou-changelog-seen-v2",
  "eagler-touhou-changelog-seen-20260822-1",
]);

export type FirstUseNoticeLoadResult =
  | Readonly<{ kind: "available" }>
  | Readonly<{ kind: "empty" }>
  | Readonly<{ kind: "error"; error: unknown }>;

export type FirstUseNoticeStorage = Pick<Storage, "getItem" | "setItem">;

export interface FirstUseNoticeControllerOptions {
  documentObj?: Document;
  storage?: FirstUseNoticeStorage | null;
  fetchImpl?: typeof fetch;
  emptyText?: () => string;
  readFailureText?: (error: unknown) => string;
  matchMediaImpl?: (query: string) => Pick<MediaQueryList, "matches">;
  setTimeoutImpl?: (callback: () => void, delay: number) => number;
}

export function getFirstUseNoticeStorage(): FirstUseNoticeStorage | null {
  try { return globalThis.localStorage ?? null; }
  catch { return null; }
}

/** Preserve the existing once-per-browser marker and pre-onboarding migrations. */
export function hasSeenFirstUseNotice(storage: FirstUseNoticeStorage | null): boolean {
  try {
    if (storage?.getItem(FIRST_USE_NOTICE_SEEN_STORAGE_KEY) === "1") return true;
    for (const key of LEGACY_SEEN_STORAGE_KEYS) {
      if (!storage?.getItem(key)) continue;
      storage.setItem(FIRST_USE_NOTICE_SEEN_STORAGE_KEY, "1");
      return true;
    }
  } catch {}
  return false;
}

/** Called after available content is displayed, never merely after a fetch. */
export function markFirstUseNoticeSeen(storage: FirstUseNoticeStorage | null): void {
  try { storage?.setItem(FIRST_USE_NOTICE_SEEN_STORAGE_KEY, "1"); } catch {}
}

function isDialogElement(value: HTMLElement): value is HTMLDialogElement {
  return "showModal" in value && typeof value.showModal === "function" &&
    "close" in value && typeof value.close === "function" &&
    "open" in value && typeof value.open === "boolean";
}

export function createFirstUseNoticeController(options: FirstUseNoticeControllerOptions = {}) {
  const documentObj = options.documentObj ?? globalThis.document;
  const storage = options.storage === undefined ? getFirstUseNoticeStorage() : options.storage;
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const emptyText = options.emptyText ?? (() => "暂无首次使用须知。");
  const readFailureText = options.readFailureText ?? (error => {
    const message = error instanceof Error ? error.message : String(error);
    return `首次使用须知读取失败：${message}。请刷新页面后重试。`;
  });
  const matchMediaImpl = options.matchMediaImpl ?? (query => globalThis.matchMedia?.(query) ?? { matches: false });
  const setTimeoutImpl = options.setTimeoutImpl ?? ((callback, delay) => globalThis.setTimeout(callback, delay));
  if (!documentObj || typeof fetchImpl !== "function") throw new Error("First-use notice requires a browser document and fetch implementation");

  const find = (id: string): HTMLElement => {
    const value = documentObj.getElementById(id);
    if (!value) throw new Error(`First-use notice element is missing: #${id}`);
    return value;
  };
  const findDialog = (id: string): HTMLDialogElement => {
    const value = find(id);
    if (!isDialogElement(value)) throw new Error(`First-use notice element must be a dialog: #${id}`);
    return value;
  };
  const dialog = findDialog("firstUseNoticeDialog");
  const target = find("firstUseNoticeText");
  let cached: FirstUseNoticeLoadResult | null = null;
  let closing = false;
  let closeGeneration = 0;

  function renderStatus(text: string, className: string): void {
    target.replaceChildren();
    const paragraph = documentObj.createElement("p");
    paragraph.className = className;
    paragraph.textContent = text;
    target.append(paragraph);
  }

  function hasSeenNotice(): boolean {
    return hasSeenFirstUseNotice(storage);
  }

  function markSeen(): void {
    markFirstUseNoticeSeen(storage);
  }

  async function load(): Promise<FirstUseNoticeLoadResult> {
    if (cached?.kind === "available" || cached?.kind === "empty") return cached;
    try {
      const response = await fetchImpl(FIRST_USE_NOTICE_FILE, { cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const html = String(await response.text()).trim();
      if (!html) {
        cached = Object.freeze({ kind: "empty" });
        renderStatus(emptyText(), "first-use-notice-empty");
        return cached;
      }
      // This HTML is generated by the repository content build, which escapes
      // raw authored HTML and filters link/image protocols before publication.
      target.innerHTML = html;
      cached = Object.freeze({ kind: "available" });
      return cached;
    } catch (error) {
      renderStatus(readFailureText(error), "first-use-notice-error");
      return Object.freeze({ kind: "error", error });
    }
  }

  async function showManual(): Promise<FirstUseNoticeLoadResult> {
    const result = await load();
    if (result.kind === "empty") renderStatus(emptyText(), "first-use-notice-empty");
    ++closeGeneration;
    closing = false;
    dialog.classList.remove("closing");
    if (!dialog.open) dialog.showModal();
    if (result.kind === "available") markSeen();
    return result;
  }

  async function maybeShowAutomatically(): Promise<boolean> {
    // This is onboarding, not a release-notes subscription. Once a browser has
    // completed the notice (or migrated a legacy seen marker), later content
    // edits must not interrupt that returning player again.
    if (hasSeenNotice()) return false;
    const result = await load();
    if (result.kind !== "available") return false;
    ++closeGeneration;
    closing = false;
    dialog.classList.remove("closing");
    if (!dialog.open) dialog.showModal();
    markSeen();
    return true;
  }

  function close(): void {
    if (!dialog.open || closing) return;
    const generation = ++closeGeneration;
    if (matchMediaImpl("(prefers-reduced-motion: reduce)").matches) { dialog.close(); return; }
    closing = true;
    dialog.classList.add("closing");
    setTimeoutImpl(() => {
      if (generation !== closeGeneration) return;
      if (dialog.open) dialog.close();
      dialog.classList.remove("closing");
      closing = false;
    }, 220);
  }

  dialog.addEventListener("cancel", event => { event.preventDefault(); close(); });
  dialog.addEventListener("click", event => { if (event.target === dialog) close(); });

  return Object.freeze({ load, showManual, maybeShowAutomatically, close, isOpen: () => dialog.open });
}
