import {authoredSourcesPlugin} from './authored-sources.mjs';
/** Actual main native-global/path contracts through fake ports, not live RTC. */
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
let dir,createGameplayNetwork;
before(async()=>{dir=await mkdtemp(resolve('.cache/gameplay-network-'));const outfile=resolve(dir,'model.mjs');await build({entryPoints:['app/models/gameplay-network.ts'],outfile,bundle:true,format:'esm',platform:'node',logLevel:'silent',plugins: [authoredSourcesPlugin(resolve())]});({createGameplayNetwork}=await import(pathToFileURL(outfile).href));});after(async()=>{if(dir)await rm(dir,{recursive:true,force:true});});
function fixture(){
 const updates=new Set(),timeouts=new Map(),intervals=new Map();let serial=0,time=0,doc={};
 const state={epoch:1,launched:true};const peer={inputOpen:false,controlOpen:false,pc:{connectionState:'connected',iceConnectionState:'connected'}};
 const transport={peers:new Map([[1,peer]]),relay:{readyState:0},failed:false,error:'',rtcReadySent:false};
 const target={Module:{eaglerOptions:{netplayMode:'lan'}},__th10PeerTransport:transport,__eaglerNetplayTransport:'rtc',__eaglerNetplayPath:'direct',__eaglerNetplayLanActive:false};
 const context={product:'th10mp',runtimeVariant:'multiplayer',spectator:false,replayViewer:false,roomCode:'ABCD',player:0,playerCount:2,inputDelay:2,adonisMode:2,adonisSupported:true};
 const runtime={getSnapshot:()=>state,getMidiEventContext:()=>({epoch:state.epoch,document:doc,target}),subscribe(fn){updates.add(fn);return()=>updates.delete(fn);}};
 const model=createGameplayNetwork({runtime,context:()=>context,english:()=>true,translate:(key,p)=>`${key}:${JSON.stringify(p??{})}`,now:()=>time,timers:{setTimeout(fn,ms){const id=++serial;timeouts.set(id,{fn,ms});return id;},clearTimeout(id){timeouts.delete(id);},setInterval(fn,ms){const id=++serial;intervals.set(id,{fn,ms});return id;},clearInterval(id){intervals.delete(id);}}});
 return{model,state,target,context,transport,peer,timeouts,intervals,advance(ms){time+=ms;},poll(){for(const[id,{fn}]of[...timeouts]){timeouts.delete(id);fn();}},replace(){doc={};for(const fn of updates)fn();}};
}
test('room/native transport connection is not ready until all actual input and control channels open',async()=>{const f=fixture();let done=false;const waiting=f.model.waitForGameplayPath({isCurrent:()=>true}).then(()=>done=true);await Promise.resolve();assert.equal(done,false);assert.equal([...f.timeouts.values()][0].ms,250);f.peer.inputOpen=true;f.poll();await Promise.resolve();assert.equal(done,false);f.peer.controlOpen=true;f.poll();await waiting;assert.equal(done,true);f.model.dispose();});
test('relay and spectator use actual launched relay socket rather than room probes',async()=>{for(const spectator of [false,true]){const f=fixture();f.context.spectator=spectator;f.target.__eaglerNetplayTransport='relay';let done=false;const wait=f.model.waitForGameplayPath({isCurrent:()=>true}).then(()=>done=true);f.poll();await Promise.resolve();assert.equal(done,false);f.transport.relay.readyState=1;f.poll();await wait;assert.equal(done,true);f.model.dispose();}});
test('ordinary runtime module does not expose MP diagnostics even selected MP metadata exists',()=>{const f=fixture();f.target.Module.eaglerOptions.netplayMode='';f.model.refresh();assert.equal(f.model.readNativeSnapshot(),null);assert.deepEqual(f.model.getSnapshot().diagnostics,{});assert.equal(f.model.getSnapshot().playerStatusVisible,false);f.model.dispose();});
test('failed path rejects original failure, timeout is120s and room/document replacement cancels',async()=>{
 const a=fixture();a.transport.failed=true;a.transport.error='channel failed';await assert.rejects(a.model.waitForGameplayPath({isCurrent:()=>true}),/channel failed/);a.model.dispose();
 const b=fixture();const timeout=b.model.waitForGameplayPath({isCurrent:()=>true});b.advance(120000);b.poll();await assert.rejects(timeout,/gameplayPathTimeout/);b.model.dispose();
 const c=fixture();const old=c.model.waitForGameplayPath({isCurrent:()=>true});c.replace();c.poll();await assert.rejects(old,{name:'AbortError',message:'EAGLER_RUNTIME_SESSION_SUPERSEDED'});c.model.dispose();
});
test('readiness disconnect overlay uses original connectedOnce and exact channel state',()=>{const f=fixture();f.peer.inputOpen=f.peer.controlOpen=true;f.model.refresh();assert.equal(f.model.getSnapshot().connection.hidden,true);f.peer.inputOpen=false;f.model.refresh();assert.equal(f.model.getSnapshot().connection.reconnecting,true);assert.equal(f.model.getSnapshot().returnToRoom,true);f.context.replayViewer=true;f.model.refresh();assert.equal(f.model.getSnapshot().connection,null);assert.equal(f.model.getSnapshot().playerStatusVisible,false);f.model.dispose();});
test('quality uses actual selected RTC pair and late stats cannot affect a replacement document',async()=>{const f=fixture();f.peer.pc.getStats=async()=>new Map([['transport',{type:'transport',selectedCandidatePairId:'pair'}],['pair',{currentRoundTripTime:.077}]]);await f.model.sampleQuality();f.model.refresh();assert.equal(f.model.getSnapshot().playerStatus[0].text,'P2 direct 77/0ms');assert.match(f.model.getSnapshot().diagnostics.runtimeNetplayQualityDiag,/77ms/);
 let resolveStats;f.peer.pc.getStats=()=>new Promise(r=>resolveStats=r);const stale=f.model.sampleQuality();f.replace();resolveStats(new Map([['pair',{type:'candidate-pair',nominated:true,state:'succeeded',currentRoundTripTime:9}]]));await stale;f.model.refresh();assert.doesNotMatch(f.model.getSnapshot().diagnostics.runtimeNetplayQualityDiag,/9000ms/);f.model.dispose();});
test('disposal rejects pending wait and retires both original250ms/1000ms intervals',async()=>{const f=fixture();assert.deepEqual([...f.intervals.values()].map(x=>x.ms),[250,1000]);const wait=f.model.waitForGameplayPath({isCurrent:()=>true});f.model.dispose();await assert.rejects(wait,{name:'AbortError',message:'EAGLER_RUNTIME_SESSION_SUPERSEDED'});assert.equal(f.timeouts.size,0);assert.equal(f.intervals.size,0);});

test('native peer/path records preserve original array rejection and entry limits',()=>{const f=fixture();f.target.__eaglerNetplayRtcPaths=[[],{peer:1,path:'direct'},{peer:2,path:'turn'},{peer:3,path:'other'}];f.target.__eaglerNetplayLanPeers=[[],{player:0},{player:1},{player:2},{player:3}];const net=f.model.readNativeSnapshot();assert.deepEqual(net.rtcPaths.map(x=>x.peer),[1,2]);assert.deepEqual(net.lanPeers.map(x=>x.player),[0,1,2]);f.model.dispose();});
