/** Main app2244–2312/2720–2749; fake authenticated event/scheduling ports only. */
import test, {before, after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
let dir,createRuntimeDiagnostics;
before(async()=>{dir=await mkdtemp(resolve('.cache/diagnostics-main-'));const outfile=resolve(dir,'model.mjs');await build({entryPoints:['app/models/runtime-diagnostics.ts'],outfile,bundle:true,format:'esm',platform:'node',logLevel:'silent'});({createRuntimeDiagnostics}=await import(pathToFileURL(outfile).href));});after(async()=>{if(dir)await rm(dir,{recursive:true,force:true});});
function fixture({saved=null,testBuild=false}={}) {
 const updates=new Set(),events=new Set(),storageEvents=new Set(),hostFrames=new Map(),childFrames=new Map(),intervals=new Map(),writes=[];let serial=0,time=0;
 let state={epoch:1,launched:false,firstFrame:false};let doc={};
 const child={requestAnimationFrame(fn){const id=++serial;childFrames.set(id,fn);return id;},cancelAnimationFrame(id){childFrames.delete(id);}};
 const frame={contentWindow:child};const runtime={getSnapshot:()=>state,getMidiEventContext:()=>({epoch:state.epoch,document:doc}),subscribe(fn){updates.add(fn);return()=>updates.delete(fn);},subscribeEvents(fn){events.add(fn);return()=>events.delete(fn);}};
 const window={requestAnimationFrame(fn){const id=++serial;hostFrames.set(id,fn);return id;},cancelAnimationFrame(id){hostFrames.delete(id);},setInterval(fn,ms){const id=++serial;intervals.set(id,{fn,ms});return id;},clearInterval(id){intervals.delete(id);},addEventListener(type,fn){storageEvents.add(fn);},removeEventListener(type,fn){storageEvents.delete(fn);}};
 const model=createRuntimeDiagnostics({runtime,browser:()=> 'Browser100',testBuild:()=>testBuild,frameLimit60:()=>false,storage:{getItem:()=>saved,setItem:(...args)=>writes.push(args)},translate:(key,p)=>`${key}:${p?.value??p?.hz??p?.count??''}`,window,frame,now:()=>time});
 return{model,setTestBuild(value){testBuild=value;model.refresh();},writes,hostFrames,childFrames,intervals,storageEvents,update(change){state={...state,...change};for(const fn of updates)fn();},event(message){for(const fn of events)fn(message);},advance(ms){time+=ms;},frames(){for(const [id,fn]of [...hostFrames]){hostFrames.delete(id);fn();}for(const [id,fn]of [...childFrames]){childFrames.delete(id);fn();}},sample(){for(const {fn}of intervals.values())fn();},replaceDocument(){doc={};}};
}
test('original test-build default and explicit stored preference apply only while launched',()=>{for(const [saved,testBuild,expected]of [[null,false,false],[null,true,true],['0',true,false],['1',false,true]]){const f=fixture({saved,testBuild});assert.equal(f.model.getSnapshot().visible,false);f.update({launched:true});assert.equal(f.model.getSnapshot().visible,expected);f.model.toggle();assert.equal(f.model.getSnapshot().enabled,!expected);assert.deepEqual(f.writes.at(-1),['eagler-touhou-runtime-diagnostics-v1',expected?'0':'1']);f.model.dispose();}});
test('original audio and frame warning thresholds remain exact, bad overrides warn',()=>{const f=fixture();f.event({event:'frame-health',fps:60,maxGapMs:35});assert.equal(f.model.getSnapshot().severity,'warn');f.event({event:'audio-health',minQueuedMs:4,backend:'worklet',underruns:0,robust:true});assert.equal(f.model.getSnapshot().severity,'bad');assert.match(f.model.getSnapshot().audio,/4ms AW/);f.event({event:'audio-health',minQueuedMs:20,backend:'script',underruns:0});f.event({event:'frame-health',fps:60,maxGapMs:34});assert.equal(f.model.getSnapshot().severity,'');f.event({event:'runtime-info',renderer:'SwiftShader'});assert.equal(f.model.getSnapshot().severity,'bad');f.model.dispose();});
test('first-frame probe counts host and child separately, resets on epoch and rejects replaced document',()=>{const f=fixture();f.update({launched:true});assert.equal(f.hostFrames.size,0);f.update({firstFrame:true});assert.equal(f.hostFrames.size,1);assert.equal(f.childFrames.size,1);f.advance(500);f.frames();f.sample();assert.match(f.model.getSnapshot().frame,/frameShort:2 - C2/);f.replaceDocument();f.advance(500);f.frames();f.sample();assert.equal(f.intervals.size,0);f.update({epoch:2,firstFrame:false,launched:false});assert.match(f.model.getSnapshot().frame,/C--/);f.model.dispose();assert.equal(f.hostFrames.size,0);assert.equal(f.childFrames.size,0);});
test('storage changes use original key and disposal unsubscribes live ports',()=>{const f=fixture({testBuild:true});for(const fn of f.storageEvents)fn({key:'eagler-touhou-runtime-diagnostics-v1',newValue:'0'});assert.equal(f.model.getSnapshot().enabled,false);f.model.dispose();assert.equal(f.storageEvents.size,0);});

test('moved from site-preferences: live manifest default is launched-only',()=>{const f=fixture();assert.equal(f.model.getSnapshot().enabled,false);f.setTestBuild(true);assert.equal(f.model.getSnapshot().enabled,true);assert.equal(f.model.getSnapshot().visible,false);f.update({launched:true});assert.equal(f.model.getSnapshot().visible,true);f.model.dispose();});
test('moved from site-preferences: explicit toggle overrides later manifest defaults',()=>{const f=fixture({testBuild:true});f.model.toggle();assert.deepEqual(f.writes.at(-1),['eagler-touhou-runtime-diagnostics-v1','0']);f.setTestBuild(false);f.setTestBuild(true);assert.equal(f.model.getSnapshot().enabled,false);f.model.dispose();});
test('moved from site-preferences: malformed preference restores manifest fallback',()=>{const f=fixture({testBuild:true,saved:'0'});assert.equal(f.model.getSnapshot().enabled,false);for(const fn of f.storageEvents)fn({key:'eagler-touhou-runtime-diagnostics-v1',newValue:'garbage'});assert.equal(f.model.getSnapshot().enabled,true);f.model.dispose();});
