/** Original metadata/copy and existing-locale-event bridge; synthetic DOM only. */
import test,{before,after,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {mkdtemp,rm} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {readOriginalBootstrap} from '../../scripts/ui-rewrite/original-bootstrap.ts';
import {installMountedDom} from './mounted-dom-environment.mjs';
const here=dirname(fileURLToPath(import.meta.url)),project=resolve(here,'../..'),require=createRequire(resolve(project,'package.json'));
let env,React,createRoot,renderToStaticMarkup,owners,work,root;
before(async()=>{env=installMountedDom();React=await import('react');({createRoot}=await import('react-dom/client'));({renderToStaticMarkup}=await import('react-dom/server'));work=await mkdtemp(resolve(here,'shell-metadata-build-'));await require('esbuild').build({absWorkingDir:project,stdin:{resolveDir:project,loader:'ts',contents:`export * from './app/components/startup/OriginalBootstrap.tsx';export * from './app/i18n.tsx';export {MemoryRouter,useNavigate} from 'react-router';`},bundle:true,platform:'node',format:'esm',jsx:'automatic',loader:{'.woff2':'dataurl','.webp':'dataurl'},outfile:resolve(work,'bundle.mjs'),logLevel:'silent',plugins:[{name:'original-source',setup(ctx){ctx.onResolve({filter:/^virtual:original-bootstrap$/},()=>({path:'original',namespace:'original'}));ctx.onLoad({filter:/.*/,namespace:'original'},()=>({contents:`export const originalBootstrap=${JSON.stringify(readOriginalBootstrap())}`,loader:'js'}));ctx.onResolve({filter:/^[^./]/},args=>({path:pathToFileURL(require.resolve(args.path)).href,external:true}));ctx.onResolve({filter:/^\.\.?\/.*\.mjs$/},args=>{const path=resolve(dirname(args.importer),args.path).replace(/\.mjs$/,'.mts');if(existsSync(path))return {path};});}}]});owners=await import(pathToFileURL(resolve(work,'bundle.mjs')));});
afterEach(async()=>{if(root)await React.act(async()=>root.unmount());root=null;env.document.body.replaceChildren();env.document.head.replaceChildren();env.document.documentElement.dataset.uiLocale='zh-CN';assert.deepEqual(env.errors.splice(0),[]);});
after(async()=>{env?.close();if(work)await rm(work,{recursive:true,force:true});});
const el=(name,props,...children)=>React.createElement(name,props,...children);
const parse=html=>new env.window.DOMParser().parseFromString(html,'text/html');
function headMarkup(path){return renderToStaticMarkup(el(owners.MemoryRouter,{initialEntries:[path]},el(owners.OriginalBootstrapHead)));}
for(const [path,locale] of [['/','zh-CN'],['/en.html','en'],['/en.html/','en']])test(`original library metadata and mobile tags ${path}`,()=>{const doc=parse(headMarkup(path));const baseline=parse(readFileSync(resolve(project,'public/index.html'),'utf8'));assert.equal(doc.title,owners.translate(locale,'site.documentTitle'));for(const node of baseline.head.querySelectorAll('meta[name],meta[property]')){const key=node.getAttribute('name')?'name':'property',value=node.getAttribute(key);if(value==='viewport')continue;const actual=doc.head.querySelector(`meta[${key}="${value}"]`);assert.ok(actual,value);const translation=node.getAttribute('data-i18n-content');assert.equal(actual.content,translation?owners.translate(locale,translation):node.content,value);}assert.equal(doc.querySelector('link[rel="canonical"]'),null,'Publication owns canonical origin');assert.equal(doc.querySelector('link[rel="manifest"]').getAttribute('href'),'site.webmanifest');assert.equal(doc.querySelector('#launcherNavigationTransition').textContent,'@view-transition{navigation:auto}');});
test('original lobby title/theme/noindex, without invented library OG/mobile metadata',()=>{const doc=parse(headMarkup('/lobby.html'));assert.equal(doc.title,owners.translate('zh-CN','lobby.title')+' ~ EAGLER TOUHOU');assert.equal(doc.querySelector('meta[name=theme-color]').content,'#111210');assert.equal(doc.querySelector('meta[name=robots]').content,'noindex');assert.equal(doc.querySelector('meta[property="og:title"]'),null);assert.equal(doc.querySelector('meta[name=description]'),null);assert.equal(doc.querySelector('meta[name=mobile-web-app-capable]'),null);assert.equal(doc.querySelector('link[rel=icon]').getAttribute('href'),'th06.ico');});
test('actual existing locale event updates unchanged lobby URL, route returns exact library tags',async()=>{let navigate;function Controller(){navigate=owners.useNavigate();return el(owners.OriginalBootstrapHead);}const container=env.document.createElement('div');env.document.body.append(container);root=createRoot(container);await React.act(async()=>root.render(el(owners.MemoryRouter,{initialEntries:['/lobby.html']},el(Controller))));assert.deepEqual(env.errors.splice(0),['Encountered a script tag while rendering React component. Scripts inside React components are never executed when rendering on the client. Consider using template tag instead (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template).'],'This synthetic createRoot check does not execute the server-emitted pre-module bootstrap');assert.equal(env.document.title,owners.translate('zh-CN','lobby.title')+' ~ EAGLER TOUHOU');await React.act(async()=>{env.document.documentElement.dataset.uiLocale='en';env.window.dispatchEvent(new env.window.CustomEvent('eagler-ui-locale-change',{detail:{locale:'en'}}));});assert.equal(env.document.title,owners.translate('en','lobby.title')+' ~ EAGLER TOUHOU');await React.act(async()=>navigate('/en.html'));assert.equal(env.document.title,owners.translate('en','site.documentTitle'));assert.equal(env.document.querySelector('meta[name=robots]'),null);assert.equal(env.document.querySelector('meta[property="og:description"]').content,owners.translate('en','site.description'));});
test('bootstrap tail still assigns unique actual module id before original watchdog',()=>{const output=renderToStaticMarkup(el(owners.OriginalBootstrapTail));assert.match(output,/script\[type="module"\]\[data-eagler-entry\]/);assert.match(output,/if\(module\)module.id='lobbyModule'/);assert.ok(output.includes(readOriginalBootstrap().lobby.script));});
