/** Main app869–926/6642–6652. Pure overlay port tests; no native game proof. */
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
let dir,createTitleNetwork;before(async()=>{dir=await mkdtemp(resolve('.cache/title-network-'));const outfile=resolve(dir,'model.mjs');await build({entryPoints:['app/models/title-network.ts'],outfile,bundle:true,format:'esm',platform:'node',logLevel:'silent'});({createTitleNetwork}=await import(pathToFileURL(outfile).href));});after(async()=>{if(dir)await rm(dir,{recursive:true,force:true});});
function fixture(){const calls=[],state={game:'th09',product:'th09',launched:true,relayUrl:'wss://relay.invalid'};const model=createTitleNetwork({context:()=>state,translate:k=>k,toast:m=>calls.push(['toast',m]),sendNetworkCancel:async()=>calls.push(['cancel']),enterRoom:(...args)=>calls.push(['enter',...args]),leaveRoom:()=>calls.push(['leave']),randomValues:a=>{a[0]=12345;return a;}});return{model,state,calls};}
test('only original supported single-player title flow opens; unsupported/mp/unlaunched stay closed',()=>{for(const patch of [{game:'th10',product:'th10'},{product:'th09mp'},{launched:false}]){const f=fixture();Object.assign(f.state,patch);f.model.open();assert.equal(f.model.getSnapshot().open,false);f.model.dispose();}const f=fixture();f.model.open();assert.equal(f.model.getSnapshot().open,true);assert.equal(f.model.getSnapshot().focusRequest,1);f.model.dispose();});
test('missing service resumes paused title with network-cancel and original toast',async()=>{const f=fixture();f.state.relayUrl='';f.model.open();await Promise.resolve();assert.deepEqual(f.calls,[['toast','multiplayer.serviceMissing'],['cancel']]);assert.equal(f.model.getSnapshot().open,false);f.model.dispose();});
test('create selects original four-digit random room and switches only overlay room state',()=>{const f=fixture();f.model.open();f.model.create();assert.deepEqual(f.calls,[['enter','th09mp','4345',true]]);assert.equal(f.model.getSnapshot().room,true);assert.equal(f.state.product,'th09');f.model.dispose();});
test('join normalizes input using main helper and empty code preserves original toast',()=>{const f=fixture();f.model.open();f.model.join();assert.deepEqual(f.calls,[['toast','status.enterRoomCode']]);f.model.setCode('12ab345');assert.equal(f.model.getSnapshot().code,'12345');f.model.join();assert.deepEqual(f.calls.at(-1),['enter','th09mp','12345',false]);f.model.dispose();});
test('close(true) resumes once, close(false) preserves actual launch sync/reset owner',async()=>{const f=fixture();f.model.open();f.model.close(true);f.model.close(true);await Promise.resolve();assert.deepEqual(f.calls,[['cancel']]);f.model.open();f.model.close(false);assert.deepEqual(f.calls,[['cancel']]);f.model.dispose();});
test('leave restores room/product/route through owner before resuming original Runtime',()=>{const f=fixture();f.model.open();f.model.create();f.calls.length=0;f.model.leave();assert.deepEqual(f.calls,[['leave'],['cancel']]);assert.deepEqual({...f.model.getSnapshot(),focusRequest:0},{open:false,room:false,code:'',focusRequest:0});f.model.dispose();});
