/** Bounded, browser-free verification of the generated visual evidence inputs.
 * Run: node tests/ui/fixtures/score-visual.check.mjs
 * This checks the real DAT parser, not the browser's import/storage flow.
 */
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';

const root=fileURLToPath(new URL('../../../',import.meta.url));
const directory=await mkdtemp(join(tmpdir(),'score-visual-fixture-'));
try {
 const output=join(directory,'fixture.mjs');
 await build({stdin:{contents:`
  export {createScoreVisualFixture} from './tests/ui/fixtures/score-visual.ts';
  export {parseScoreDat} from './src/launcher/score-dat.mts';
  export {favoriteLoadout,orderedScoreSections} from './src/launcher/score-panel.mts';
 `,resolveDir:root},outfile:output,platform:'node',format:'esm',bundle:true});
 const {createScoreVisualFixture,parseScoreDat,favoriteLoadout,orderedScoreSections}=await import(pathToFileURL(output));
 const original=[{title:'单局详细统计'},{title:'排行榜'},{title:'游玩次数'}];
 assert.deepEqual(orderedScoreSections({sections:original}).map(section=>section.title),['排行榜','游玩次数','单局详细统计']);
 assert.equal(original[0].title,'单局详细统计');
 for(const game of ['th07','th08']) {
  const fixture=createScoreVisualFixture(game),before=Buffer.from(fixture.bytes);
  const report=parseScoreDat(game,fixture.bytes);
  assert.equal(report.highest,fixture.highest);
  assert.equal(report.rankingCount,1);
  assert.deepEqual(favoriteLoadout(report),{name:fixture.favorite,count:fixture.count,portraits:fixture.portraits});
  assert.deepEqual(fixture.bytes,before,'parsing must not mutate generated bytes');
  assert.deepEqual(createScoreVisualFixture(game).bytes,before,'fixtures must be deterministic');
  assert.equal(report.notes.length,0,'fixtures contain only supported blocks');
  assert.throws(()=>parseScoreDat(game==='th07'?'th08':'th07',fixture.bytes));
  assert.throws(()=>parseScoreDat(game,fixture.bytes.subarray(0,16)));
  const corrupted=Buffer.from(fixture.bytes);corrupted[corrupted.length-1]^=128;
  assert.throws(()=>parseScoreDat(game,corrupted),'a corrupt imported DAT must be rejected');
  console.log(`PASS ${game}: ${fixture.bytes.length} generated bytes; ${fixture.highest} points; ${fixture.favorite} × ${fixture.count}; ${fixture.portraits.join(' + ')}`);
 }
} finally {
 await rm(directory,{recursive:true,force:true});
}
