/** Synthetic installer boundary: checks queue-time declarations and forwarding to
 * the existing atomic installer fence. IndexedDB transaction coverage is separate. */
import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {existsSync} from 'node:fs';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {build} from 'esbuild';
const root=fileURLToPath(new URL('../..',import.meta.url)),dir=await mkdtemp(join(tmpdir(),'published-fence-'));after(()=>rm(dir,{recursive:true,force:true}));
const sources={name:'contracts',setup(b){b.onResolve({filter:/\.mjs$/},args=>{if(!args.path.startsWith('.'))return;const path=resolve(dirname(args.importer),args.path),facade=['product-catalog','release-catalog'].find(name=>path===resolve(root,`${name}.mjs`));if(facade)return {path:resolve(root,`src/contracts/${facade}.mts`)};const authored=path.replace(/\.mjs$/,'.mts');if(authored.startsWith(join(root,'src')+'/')&&existsSync(authored))return {path:authored};});}};
const mocked={name:'installer-port',setup(b){b.onResolve({filter:/package-installer\.mjs$/},()=>({path:'installer',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const installPackageFromRemote=(...args)=>globalThis.__publishedInstaller(...args);',loader:'js'}));}};
const built=await build({entryPoints:[join(root,'package/package-launcher.mjs')],bundle:true,format:'esm',platform:'browser',write:false,plugins:[mocked,sources]});const path=join(dir,'launcher.mjs');await writeFile(path,built.outputFiles[0].text);const {installPublishedPackage}=await import(pathToFileURL(path).href);
function fixture(){const files={data:{source:'games/th11/th11.dat',target:'/th11.dat',revision:'data',bytes:1,sha256:'a'.repeat(64)},ogg:{source:'games/th11/music/ogg/track.ogg',target:'/music/track.ogg',revision:'ogg',bytes:1,sha256:'b'.repeat(64)}};const descriptor={schema:'eagler-touhou/package/1',game:'th11',revision:'revision-one',files,base:{files:['data']},components:{ogg:{type:'ogg',files:['ogg']}},runtimeRequirement:{protocol:'eagler-touhou/1',target:'th11',dataFile:'data'}};const current={installation:{game:'th11',currentGeneration:'generation-one',source:'local'},generation:{id:'generation-one',game:'th11',descriptor:structuredClone(descriptor),files:{data:{objectId:'data',revision:'data'}}}};const options={catalog:{schema:'eagler-touhou/release-catalog/1',games:{th11:{revision:descriptor.revision,descriptor:'th11.package.json'}}},catalogUrl:'https://example.test/release-catalog.json',addFileIds:['ogg'],preserveLocalSource:true,expectedGenerationId:'generation-one',expectedCurrentRevision:descriptor.revision,expectedFileDeclarations:structuredClone(files),fetchImpl:async()=>new Response(JSON.stringify(descriptor))};return {descriptor,current,options};}
test('published optional acquisition forwards exact generation fence and checks original DATA/track declarations under queue callback',async()=>{const f=fixture();let calls=0;globalThis.__publishedInstaller=async(descriptor,options)=>{calls++;assert.equal(options.expectedGenerationId,'generation-one');assert.equal(options.source(f.current),'local');assert.deepEqual(options.desiredFileIds(f.current),['data','ogg']);return f.current;};await installPublishedPackage('th11',f.options);assert.equal(calls,1);});
test('a queued different revision or same-revision DATA declaration is rejected before mutation',async()=>{for(const change of [f=>f.current.generation.descriptor.revision='revision-two',f=>f.current.generation.descriptor.files.data.sha256='c'.repeat(64)]){const f=fixture();globalThis.__publishedInstaller=async(_descriptor,options)=>{change(f);options.desiredFileIds(f.current);assert.fail('must stop before stage');};await assert.rejects(installPublishedPackage('th11',f.options),/changed before optional/);}});
test('same-revision publication rewrite is rejected against captured declarations',async()=>{const f=fixture();f.descriptor.files.ogg.target='/music/changed.ogg';globalThis.__publishedInstaller=async(_descriptor,options)=>{options.desiredFileIds(f.current);assert.fail('must stop before stage');};await assert.rejects(installPublishedPackage('th11',f.options),/declarations changed/);});
test('fence declaration input is copied before asynchronous publication fetch',async()=>{const f=fixture();let resolve,started;const began=new Promise(yes=>started=yes),wait=new Promise(yes=>resolve=yes);f.options.fetchImpl=async()=>{started();await wait;return new Response(JSON.stringify(f.descriptor));};globalThis.__publishedInstaller=async(_descriptor,options)=>{assert.deepEqual(options.desiredFileIds(f.current),['data','ogg']);return f.current;};const task=installPublishedPackage('th11',f.options);await began;f.options.expectedFileDeclarations.data.sha256='d'.repeat(64);resolve();await task;});
